# Generated by Django 3.0.5 on 2020-06-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
